name: Run multicorn2 Tests

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  run_tests:
    name: run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26

      # Binary cache is maintained in update_cache.yml; see comments there for details.
      - uses: zombiezen/setup-nix-cache-action@v0.4.0
        with:
          substituters: s3://mfenniak-multicorn2-nix-cache?region=us-west-2
          trusted_public_keys: mfenniak-multicorn2-nix-cache:mldk0J26tzkCmqihQKOiyuAm1HAs2CHdIZC0ESr56ZA=

      - run: cat /home/runner/work/_temp/setup-nix-cache-action-*/post-build-hook

      # Run all the tests.
      - run: nix build .#allTestSuites
